name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:

jobs:
  build-x86_64-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: sudo rm -rf /usr/local/lib/android /opt/ghc
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: tenpureto
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
          extraPullNames: iohk
      - name: Build
        run: nix-build -A static.tenpureto.components.exes.tenpureto
        timeout-minutes: 300
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: tenpureto-x86_64-linux
          path: result/bin/tenpureto
  package-x86_64-linux:
    runs-on: ubuntu-latest
    needs: build-x86_64-linux
    strategy:
      matrix:
        packaging: [ rpm, deb ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/download-artifact@v1
        with:
          name: tenpureto-x86_64-linux
      - name: Read package.yaml
        uses: CumulusDS/get-yaml-paths-action@v0.0.3
        id: package
        with:
          file: package.yaml
          name: name
          version: version
          homepage: homepage
          synopsis: synopsis
          author: author
      - name: Generate shell completions
        shell: bash
        run: |
          chmod +x ./tenpureto-x86_64-linux/tenpureto
          mkdir -p bash_completions zsh_completions dist
          ./tenpureto-x86_64-linux/tenpureto --bash-completion-script /usr/bin/tenpureto >bash_completions/tenpureto
          ./tenpureto-x86_64-linux/tenpureto --zsh-completion-script /usr/bin/tenpureto >zsh_completions/_tenpureto
      - name: Package ${{ matrix.packaging }}
        uses: docker://ansemjo/fpm:latest
        with:
          args:
            --input-type dir
            --output-type "${{ matrix.packaging }}"
            --force
            --package dist/
            --name "${{ steps.package.outputs.name }}"
            --version "${{ steps.package.outputs.version }}"
            --url "${{ steps.package.outputs.homepage }}"
            --description "${{ steps.package.outputs.synopsis }}"
            --maintainer "${{ steps.package.outputs.author }}"
            --depends git
            --deb-no-default-config-files
            ./tenpureto-x86_64-linux/tenpureto=/usr/bin/
            ./bash_completions/tenpureto=/etc/bash_completion.d/
            ./zsh_completions/_tenpureto=/usr/share/zsh/site-functions/
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: tenpureto-x86_64-linux.${{ matrix.packaging }}
          path: dist/
